import Head from 'next/head'
import React from 'react'
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableContainer from '@mui/material/TableContainer';
import TableHead, { tableHeadClasses } from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper, { paperClasses } from '@mui/material/Paper';
import { styled } from '@mui/material/styles';
import TableCell, { tableCellClasses } from '@mui/material/TableCell';
import Link from 'next/link';

function createData(
  name: string,
  amount: number,
  status: string,
) {
  return { name, amount: `${amount.toLocaleString()} XAF`, status };
}

const rows = [
  createData('In proident tempor', 15000, 'Ongoing'),
  createData('consequat cupidatat adipisicing amet.', 15000, 'Complete'),
  createData('Proident aliqua culpa eu aliqua et et in.', 15000, 'Complete'),
];

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    // backgroundColor: 'red',
    color: '#12033ACC',
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: 14,
    padding: '6px',
    color: '#12033ACC'
  },
}));

const StyledPaperClasses = styled(Paper)(({ theme }) => ({
  [`&.${paperClasses.elevation}`]: {
    boxShadow: 'none',
    border: '1px solid #CFCFDB',
    borderRadius: 12,
    backgroundColor: '#F1F3FA'
  },
}));


const StyledTableHead = styled(TableHead)(({ theme }) => ({
  [`&.${tableHeadClasses.root}`]: {
    backgroundColor: '#4C51C6',
    color: 'white'
  },
}));

const StyledTableHeaderCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    fontSize: 16,
    color: '#FFFFFF'
  },
}));

export const Funds = () => {
  return (
    <div className="h-screen min-h-screen flex bg-white">
      <Head>
        <title>Fundbox app</title>
        <meta name="description" content="Generated by Fundbox app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full flex flex-col'>
        <h1 className='mt-5 text-dark_blue-100 text-3xl text-center font-semibold tracking-[-1px]'>Active Funds</h1>

        <div className='mx-5 mt-5'>
          <TableContainer component={StyledPaperClasses}>
            <Table sx={{ width: '100%' }} size="small" aria-label="a dense table">
              <StyledTableHead>
                <TableRow>
                  <StyledTableHeaderCell width={'45%'}>Name</StyledTableHeaderCell>
                  <StyledTableHeaderCell align="center" width={'30%'}>Amount</StyledTableHeaderCell>
                  <StyledTableHeaderCell align="center" width={'25%'}>Status</StyledTableHeaderCell>
                </TableRow>
              </StyledTableHead>
              <TableBody>
                {rows.map((row, index) => (
                  <TableRow
                    key={row.name}
                    sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                  >
                    <StyledTableCell component="th" scope="row">
                      <Link href={`/funds/${index}`}>
                        {row.name}
                      </Link>
                    </StyledTableCell>
                    <StyledTableCell align="center">
                      <Link href={`/funds/${index}`}>{row.amount}</Link>
                    </StyledTableCell>
                    <StyledTableCell align="center">
                      <div className={
                          `text-[12px] py-[2px] rounded-xl text-white 
                          ${row.status === 'Complete' ? 'bg-success' : 'bg-grey_disabled'}`
                        }>
                        {row.status}
                      </div>
                    </StyledTableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </div>
      </main>
    </div>
  )
}

export default Funds;