import Head from 'next/head'
import React from 'react'
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableContainer from '@mui/material/TableContainer';
import TableHead, { tableHeadClasses } from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper, { paperClasses } from '@mui/material/Paper';
import { styled } from '@mui/material/styles';
import TableCell, { tableCellClasses } from '@mui/material/TableCell';
import Link from 'next/link';

function createData(
  name: string,
  amount: number,
) {
  return { name, amount: `${amount.toLocaleString()} XAF` };
}

const rows = [
  createData('Xurro', 5000),
  createData('Abdoul', 2500),
  createData('Nasser', 25000),
];

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    color: '#12033ACC',
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: 14,
    color: '#12033ACC'
  },
}));

const StyledPaperClasses = styled(Paper)(({ theme }) => ({
  [`&.${paperClasses.elevation}`]: {
    boxShadow: 'none',
    border: '1px solid #CFCFDB',
    borderRadius: 12,
    backgroundColor: '#F1F3FA'
  },
}));


const StyledTableHead = styled(TableHead)(({ theme }) => ({
  [`&.${tableHeadClasses.root}`]: {
    backgroundColor: '#4C51C6',
    color: 'white'
  },
}));

const StyledTableHeaderCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    fontSize: 16,
    color: '#FFFFFF'
  },
  [`&.${tableCellClasses.root}`]: {
    backgroundColor: 'transparent'
  },
}));

export const FundDetails = () => {
  return (
    <div className="h-screen min-h-screen flex bg-white">
      <Head>
        <title>Fundbox app</title>
        <meta name="description" content="Generated by Fundbox app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full flex flex-col'>
        <h1 className='mt-5 text-dark_blue-100 text-3xl text-center font-semibold tracking-[-1px]'>Bossman birthday fund to gather money for the party</h1>

        <div className='mx-5 mt-5 flex-1'>
          <TableContainer component={StyledPaperClasses} sx={{ maxHeight: 'calc(100vh - 205px)' }}>
            <Table sx={{ width: '100%' }} size="small" stickyHeader aria-label="a dense table">
              <StyledTableHead>
                <TableRow>
                  <StyledTableHeaderCell width={'50%'}>Name</StyledTableHeaderCell>
                  <StyledTableHeaderCell width={'50%'}>Amount</StyledTableHeaderCell>
                </TableRow>
              </StyledTableHead>
              <TableBody>
                {rows.map((row, index) => (
                  <TableRow
                    key={row.name}
                    sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                  >
                    <StyledTableCell component="th" scope="row">
                      <Link href={`/funds/${index}`}>
                        {row.name}
                      </Link>
                    </StyledTableCell>
                    <StyledTableCell>{row.amount}</StyledTableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </div>

        <div className='m-5'>
          <button className='bg-blue-100 w-full h-14 rounded-2xl text-white font-medium leading-6 tracking-[-0.3px] disabled:opacity-50'>
            Mark as Complete
          </button>
        </div>
      </main>
    </div>
  )
}

export default FundDetails;