version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fundbox_db
    restart: always
    environment:
      POSTGRES_DB: communityfunds
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: community-funds-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: communityfunds
    ports:
      - "8080:8080"

  frontend:
    build: ./client
    container_name: nextjs-client
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
  