services:
  - name: community-funds
    type: web
    runtime: go
    repo: https://github.com/xurror/fundbox
    branch: main
    region: frankfurt
    plan: free
    buildCommand: make build
    startCommand: ./server/.build/community-funds
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_DSN
        fromDatabase:
          name: fundbox
          property: connectionString
      - fromGroup: community-funds
