services:
  - name: community-funds
    type: web
    runtime: docker
    repo: https://github.com/xurror/fundbox
    branch: main
    region: frankfurt
    plan: free
    rootDir: ./server
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_DSN
        fromDatabase:
          name: community-funds-db
          property: connectionString
      - fromGroup: community-funds
