import '../styles/globals.css'
import { ApolloProvider } from "@apollo/client";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <ApolloProvider client={client}> */}
        <UserProvider>
          <body>{children}</body>
        </UserProvider>
      {/* </ApolloProvider> */}
    </html>
  );
}
