import Head from 'next/head'
import { ChangeEvent, useState } from 'react';
import LinearProgress from '@mui/material/LinearProgress';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import TextField from '@mui/material/TextField';
import InputAdornment from '@mui/material/InputAdornment';

export const Fund = () => {
  const [form, setForm] = useState({
    name: '',
    amount: '',
    number: '',
    paymentMethod: '',
    disabled: false
  });
  const [fund, setFund] = useState({
    name: 'Raise money for bossman',
    description: 'We need to contribute some cash for bossman\'s birthday',
  });
  const [progress, setProgress] = useState(15);
  const [paymentMethod, setPaymentMethod] = useState('');

  const create = () => {
    let _form: any = {...form}
    _form.disabled = true;
    setForm(_form);
    setProgress(85)
  }

  const updateForm = (value: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>, field: string) => {
    if (field === 'name') setProgress(30)
    if (field === 'number') setProgress(45)
    if (field === 'amount') setProgress(60)
    let _form: any = {...form}
    _form[field] = value.target.value
    setForm(_form)
  }

  const handleChange = (event: SelectChangeEvent) => {
    setPaymentMethod(event.target.value);
    setProgress(80)
  };

  return (
    <div className="h-screen min-h-screen flex bg-white">
      <Head>
        <title>Fundbox app</title>
        <meta name="description" content="Generated by Fundbox app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full flex flex-col'>
        <div className='w-full mt-10 mb-6 flex items-center justify-center'>
          <LinearProgress
            variant="determinate"
            value={progress}
            className='w-1/2 h-2 rounded'
          />
        </div>

        <div className='flex flex-1 flex-col items-center'>
          <div className='mx-6'>
            <h1 className='text-dark_blue-100 text-4xl text-center font-semibold tracking-[-1px]'>{fund.name}</h1>
            <p className='text-dark_blue-80 text-lg text-center'>{fund.description}</p>
          </div>

          <div className='w-full p-6 mt-6 mx-6'>
            <FormControl className='mt-4' fullWidth>
              <TextField 
                id="outlined-basic" 
                label="Name"
                variant="outlined"
                type='text'
                onChange={(e) => updateForm(e, 'name')}
                disabled={form.disabled}
              />
            </FormControl>

            <FormControl className='mt-4' fullWidth>
              <TextField 
                id="outlined-basic" 
                label="Nmber"
                variant="outlined"
                type='number'
                onChange={(e) => updateForm(e, 'number')}
                disabled={form.disabled}
              />
            </FormControl>

            <FormControl className='mt-4' fullWidth>
              <TextField 
                id="outlined-basic" 
                label="Amount"
                variant="outlined"
                type='number' 
                InputProps={{
                  startAdornment: <InputAdornment position="start">XAF</InputAdornment>
                }}
                onChange={(e) => updateForm(e, 'amount')}
                disabled={form.disabled}
              />
            </FormControl>
            
            <FormControl  className='mt-4' fullWidth>
              <InputLabel id="demo-simple-select-label">Payment method</InputLabel>
              <Select
                labelId="demo-simple-select-label"
                id="demo-simple-select"
                value={paymentMethod}
                label="Payment method"
                onChange={handleChange}
                disabled={form.disabled}
              >
                <MenuItem value={'momo'}>MTN Mobile Money</MenuItem>
                <MenuItem value={'om'}>Orange Money</MenuItem>
              </Select>
            </FormControl>
          </div>
          <div className='w-full px-6 my-5 mt-20'>
            <button
              className='bg-blue-100 w-full h-14 rounded-2xl text-white font-medium leading-6 tracking-[-0.3px] disabled:opacity-50'
              disabled={form.disabled}
              onClick={() => create()}
            >Submit</button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Fund;