import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Countries from "../components/Countries";

export default function Home() {
  return (
    <div className="h-screen min-h-screen flex flex-col justify-center items-center px-[250px] bg-basic-200">
      <Head>
        <title>Fundbox app</title>
        <meta name="description" content="Generated by Fundbox app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col flex-1 w-full">
        <div className='py-14 border-b border-basic-500'>
          <h1 className="text-4xl font-bold">Create a Fund</h1>
          <p className="text-md text-basic-600 pt-1">Create a fund, copy and share the link with your friends!</p>
        </div>

        <div className='flex flex-1'>
          <div className='w-1/3 border-r border-basic-500 p-10'>
            <div>steps 1</div>
            <div>steps 2</div>
            <div>steps 3</div>
          </div>
          <div className='w-2/3 p-10'>
            inputs
          </div>
        </div>
      </main>
    </div>
  )
}
