package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	appContext "getting-to-go/context"
	"getting-to-go/graph/generated"
	"getting-to-go/model"
	"getting-to-go/util"
	"github.com/google/uuid"
)

// Funds is the resolver for the funds field.
func (r *queryResolver) Funds(ctx context.Context, limit *int, offset *int) ([]*model.Fund, error) {
	return r.FundService.GetFunds(util.GetLimitAndOffset(limit, offset))
}

// Fund is the resolver for the fund field.
func (r *queryResolver) Fund(ctx context.Context, id uuid.UUID) (*model.Fund, error) {
	return r.FundService.GetFund(id)
}

// FundContributions is the resolver for the fundContributions field.
func (r *queryResolver) FundContributions(ctx context.Context, fundID *uuid.UUID, limit *int, offset *int) ([]*model.Contribution, error) {
	l, o := util.GetLimitAndOffset(limit, offset)
	return r.FundService.GetFundContributions(*fundID, l, o)
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*model.User, error) {
	return appContext.CurrentUser(ctx), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	return r.UserService.GetUser(id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*model.User, error) {
	return r.UserService.GetUsers(util.GetLimitAndOffset(limit, offset))
}

// UserContributions is the resolver for the userContributions field.
func (r *queryResolver) UserContributions(ctx context.Context, userID uuid.UUID, limit *int, offset *int) ([]*model.Contribution, error) {
	l, o := util.GetLimitAndOffset(limit, offset)
	return r.ContributionService.GetContributionsByUserID(userID, l, o)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
