package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"fmt"
	"getting-to-go/graph/generated"
	models "getting-to-go/model"
	utils "getting-to-go/util"

	"github.com/google/uuid"
)

// Funds is the resolver for the funds field.
func (r *queryResolver) Funds(ctx context.Context, limit *int, offset *int) ([]*models.Fund, error) {
	panic(fmt.Errorf("not implemented: Funds - funds"))
}

// Fund is the resolver for the fund field.
func (r *queryResolver) Fund(ctx context.Context, id uuid.UUID) (*models.Fund, error) {
	panic(fmt.Errorf("not implemented: Fund - fund"))
}

// FundContributions is the resolver for the fundContributions field.
func (r *queryResolver) FundContributions(ctx context.Context, fundID *uuid.UUID, limit *int, offset *int) ([]*models.Contribution, error) {
	panic(fmt.Errorf("not implemented: FundContributions - fundContributions"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*models.User, error) {
	return r.userService.GetUsers(utils.GetLimitAndOffset(limit, offset))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*models.User, error) {
	return r.userService.GetUser(id)
}

// UserContributions is the resolver for the userContributions field.
func (r *queryResolver) UserContributions(ctx context.Context, userID uuid.UUID, limit *int, offset *int) ([]*models.Contribution, error) {
	l, o := utils.GetLimitAndOffset(limit, offset)
	return r.contributionService.GetContributionsByUserID(userID, l, o)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
