package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.32

import (
	"context"
	"getting-to-go/graph/generated"
	models "getting-to-go/model"
)

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *models.User) ([]models.Role, error) {
	return models.ConvertToRoleArray(obj.Roles), nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
