basePath: /api
definitions:
  dto.ContributionDTO:
    properties:
      amount:
        type: number
      anonymous:
        type: boolean
      contributorId:
        description: Null if anonymous
        type: string
      contributorName:
        description: Null if anonymous
        type: string
      createdAt:
        type: string
      fundId:
        type: string
      fundName:
        type: string
      id:
        type: string
    type: object
  dto.FundDTO:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      targetAmount:
        type: number
      updatedAt:
        type: string
    type: object
  models.Contribution:
    properties:
      amount:
        type: number
      anonymous:
        type: boolean
      contributor:
        allOf:
        - $ref: '#/definitions/models.User'
        description: The user who made the contribution
      contributorID:
        description: Nullable for anonymous contributions
        type: string
      createdAt:
        type: string
      fund:
        allOf:
        - $ref: '#/definitions/models.Fund'
        description: Relationships
      fundID:
        type: string
      id:
        type: string
      updatedAt:
        type: string
    type: object
  models.Fund:
    properties:
      contributions:
        description: Contributions to this fund
        items:
          $ref: '#/definitions/models.Contribution'
        type: array
      createdAt:
        type: string
      id:
        type: string
      manager:
        allOf:
        - $ref: '#/definitions/models.User'
        description: Relationships
      managerID:
        type: string
      name:
        type: string
      targetAmount:
        type: number
      updatedAt:
        type: string
    type: object
  models.User:
    properties:
      auth0ID:
        description: Maps to Auth0 user
        type: string
      contributions:
        description: Contributions made
        items:
          $ref: '#/definitions/models.Contribution'
        type: array
      createdAt:
        type: string
      email:
        type: string
      fundsManaged:
        description: Relationships
        items:
          $ref: '#/definitions/models.Fund'
        type: array
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for the Community Funds system
  title: Community Funds API
  version: "1.0"
paths:
  /contributions:
    get:
      consumes:
      - application/json
      description: Returns all contributions made to a specific fund, including contributor
        details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ContributionDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get contributions for a fund
      tags:
      - contributions
    post:
      consumes:
      - application/json
      description: Anyone can contribute to a fund, authenticated users are tracked,
        anonymous users are allowed
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Contribution'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Make a contribution
      tags:
      - contributions
  /funds:
    get:
      consumes:
      - application/json
      description: Returns a list of all funds where the authenticated user is the
        manager
      parameters:
      - description: Fund ID
        in: path
        name: fundId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FundDTO'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all funds managed by the authenticated user
      tags:
      - funds
    post:
      consumes:
      - application/json
      description: Fund managers can create a fund with a target amount
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.FundDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a fund
      tags:
      - funds
  /funds/contributed:
    get:
      consumes:
      - application/json
      description: Returns a list of all funds a user has contributed to but does
        not manage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.FundDTO'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get funds contributed to
      tags:
      - funds
  /health:
    get:
      description: Returns API health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - actuator
  /ready:
    get:
      description: Returns readiness status based on database connectivity
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Readiness Probe
      tags:
      - actuator
  /restart:
    post:
      description: Simulates an API restart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Restart API
      tags:
      - actuator
  /shutdown:
    post:
      description: Terminates the application gracefully
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Shutdown API
      tags:
      - actuator
swagger: "2.0"
